MAP_SIZE_X = 32
MAP_SIZE_Y = 16
MAX_NUM_SECTIONS = 5
MIN_NUM_SECTIONS = 2
MAX_NUM_ROOMS = 5
MIN_NUM_ROOMS = 2

MIN_SECTION_SIZE = 7
ROOM_PADDING = 1
MIN_ROOM_FLOOR_SIZE = 3

MIN_NUM_RATION = 1
MAX_NUM_RATION = 3

